### PR TITLE
Icons Added

### PR DESCRIPTION
**Pull request by YaverJavid**
I have changed all the icons, created them by myself

### CODE REVIEW

**Comment by Iyusuf40** [comment]
Wow Yaver, you must have put in a lot of time to come up with these drawings.
They are beautiful.
I think they are all beautiful and pretty self-explanatory except the arrangement icons (send to back/front, forward and backward), They are not as obvious as the others.

Nice drawings.

**Comment by gniziemazity** [comment]
Amazing @YaverJavid! But I agree with @Iyusuf40. Could those (back/front, forward and backward) be updated to be more intuitive, somehow? They look more polished than mine, but mine are more intuitive (to me, at least).

**Comment by YaverJavid** [comment]
I changed the said icons, although i would still insist keeping new ones, they are already used.

**Comment by Iyusuf40** [comment]
> I changed the said icons, although i would still insist keeping new ones, they are already used.

Yea, they are beautiful, I see you redesigned the arrangement section icons. 
You swapped them though, I mean the `send to back` icon was switched with `bring to front` icon. I think they should be swapped.
Please take a look.

Thanks.

**Comment by YaverJavid** [comment]
fixed that too

**Comment by Iyusuf40** [comment]
> fixed that too

Thank you Yaver.

Now the `Send Backward` and `Bring Forward` icons are flipped, can you please swap them.
Send Backward should be ⬆️ while Bring forward should be ⬇️.
Sorry I'm bothering you too much.

If you do not have the time, I'm sure Radu will fix it whilst merging.

**Comment by YaverJavid** [comment]
done

**Comment by Iyusuf40** [comment]
> done

Beautiful Work Yaver, Thank you and everything looks good to me.

**Comment by gniziemazity** [comment]
Nice work @YaverJavid, but I still see some problems. To me, all those: back, bwd, front and fwd look like they are pushing things to the back. The front and fwd ones just do it from the top, somehow. But in my (ugly) version, I tried to make the arrows look like they are coming towards us, instead.

Another small thing is, even though, I know 'A' is often symbol for text, I think that 'T' is better because it also shows what the shortcut character for activating that tool is. You may try stylizing it differently (maybe using serifs) and see what you think.

Good if @Iyusuf40 also comments on these before you do anything. It's always good to have more opinions on interface-related stuff.

**Comment by Iyusuf40** [comment]
Yes indeed, I agree with you. 

> Nice work @YaverJavid, but I still see some problems. To me, all those: back, bwd, front and fwd look like they are pushing things to the back. The front and fwd ones just do it from the top, somehow. But in my (ugly) version, I tried to make the arrows look like they are coming towards us, instead.
> 
> Another small thing is, even though, I know 'A' is often symbol for text, I think that 'T' is better because it also shows what the shortcut character for activating that tool is. You may try stylizing it differently (maybe using serifs) and see what you think.
> 
> Good if @Iyusuf40 also comments on these before you do anything. It's always good to have more opinions on interface-related stuff.

Yes indeed I agree with you. I think making it narrower at far ends to show distance and direction makes it more self descriptive.

I think the title attribute of the shape tools already took care of telling users shortcuts for the tools in case of the 'A' icon for the texf tool

**Comment by gniziemazity** [comment]
Merged this now @YaverJavid, but still waiting for that update I requested above.
And yes, @Iyusuf40, you are right, but title says one thing 't' and the icon says another thing 'A'. Conflicting indicators like that don't make for a good experience, in general.

**Comment by Iyusuf40** [comment]
> but title says one thing 't' and the icon says another thing 'A'. Conflicting indicators like that don't make for a good experience, in general.

Missed this part. Its important for the title and the Icon itself to match

**Comment by YaverJavid** [comment]
I didn't have access to network for some reason. I personally use affinity designer, I made icons in it. I took inspiration from it. Fwd, Bwd, Back, Front cons were very abstract. Icons get meaning associated with with, purely they don't usually have a value. 

For example this icon, 🪄 the sparkles in it, are used as a symbol for AI.

**Comment by gniziemazity** [comment]
> I didn't have access to network for some reason. I personally use affinity designer, I made icons in it. I took inspiration from it. Fwd, Bwd, Back, Front cons were very abstract. Icons get meaning associated with with, purely they don't usually have a value.
> 
> For example this icon, 🪄 the sparkles in it, are used as a symbol for AI.

Icons should have clear meaning... Those that don't mean anything and people just have to learn what they mean, are bad icons, I think. I didn't just draw my arrows straight up (down) in my versions. They were supposed to look like moving towards the back or towards the front, because, as you look at the screen, the items and layers are arranged in that way. I also decided to use the bottom variants because we are used to see arrows like that on the ground, in the real world (like when driving)
image

I don't know how clear my design is... probably not very :-D but trying out different things and not sticking to some existing set is the only way to find out. As for the AI one, the magic wand is an OK fit because modern AI works like magic. People press it and wait, wondering what surprise they're gonna get. Now... it's not the best fit because many software used the magic wand to be a different tool that helps segment / select images, but I feel that tool is going out of use nowadays (it was still useful few years ago, but now the main thing it was used for = selecting subjects is done much easier). I believe what is happening is they are repurposing a tool that is (almost) obsolete.

**Pull request merged**
