### PR TITLE
move text edit history management to HistoryTools

### PR DESCRIPTION
**Pull request by Iyusuf40**
- `HistoryTools` now responsible for handling text edit changes
- fixed a minor bug where text edit redo stack is requires 2 or more clicks before reversing to previous state

### CODE REVIEW

**Comment by gniziemazity** [comment]
Yes, those functions belong to the history tools, however, I also imagine this tool you're building could be used by others as well, in any project that requires a text editor on the canvas. In that case, encapsulating undo/redo in the tool itself could be the way to go (just thinking out loud).

**Comment by pieterdeschepper** [comment]
If you make it event-based, you can have best of both worlds

**Comment by gniziemazity** [comment]
> If you make it event-based, you can have best of both worlds

Wouldn't that mean you need to reimplement undo/redo using those events in some other app?

**Comment by Iyusuf40** [comment]
In this [PR](https://github.com/gniziemazity/advanced_drawing_app/pull/54), I have tried to encapsulate the editor limiting dependencies to only `Vector` class and `rotateCanvas` function.

**Pull request merged**
