### PR TITLE
Refactor/properties panel

### PR DESCRIPTION
**Pull request by pieterdeschepper**
This refactors the whole properties panel.
- Not static anymore
- Each section of the panel is it's own class that defines the properties, layout, and functionality
- Each section automatically updates its values when needed
- Each section has a minimize option now

### CODE REVIEW

**Comment by Iyusuf40** [comment]
Nice update.

The minimize button improves the UI in a nice way, reduces clutter.
beautiful panelProperties refactor. It will be way more easier to add properties now.
And my typos :), how those typos have escaped Radu and I for several weeks I don't know, lol.

Thank you Pieter.

**Comment by Iyusuf40** [comment]
I just noticed a small mistake in the way we called 2 functions, in
`FiltersSection.changeChromaKey` and `FiltersSection.changeChromaThreshold`
what we want is
```
viewport.getSelectedShapes().forEach((s) => s.filters[index].setKeyFromHex(value, save));
```
and
```
viewport.getSelectedShapes().forEach((s) => s.filters[index].setThreshold(value, save));
```
not
```
viewport.getSelectedShapes().forEach((s) => s.filters[index].setKeyFromHex(value), save);
```
emphasis on where the `save` argument is passed.

We also may need to change the `Chroma.setKeyFromHex` and `Chroma.setThreshold` method signatures to take in the `save` parameter.

BTW, this mistake has been there even before this PR.

**Comment by pieterdeschepper** [comment]
> I just noticed a small mistake in the way we called 2 functions, in `FiltersSection.changeChromaKey` and `FiltersSection.changeChromaThreshold` what we want is
> 
> ```
> viewport.getSelectedShapes().forEach((s) => s.filters[index].setKeyFromHex(value, save));
> ```
> 
> and
> 
> ```
> viewport.getSelectedShapes().forEach((s) => s.filters[index].setThreshold(value, save));
> ```
> 
> not
> 
> ```
> viewport.getSelectedShapes().forEach((s) => s.filters[index].setKeyFromHex(value), save);
> ```
> 
> emphasis on where the `save` argument is passed.
> 
> We also may need to change the `Chroma.setKeyFromHex` and `Chroma.setThreshold` method signatures to take in the `save` parameter.
> 
> BTW, this mistake has been there even before this PR.

Yes, this was just copied over during the refactoring.
I've updated the code to reflect your proposed changes

**Comment by Iyusuf40** [comment]
> > I just noticed a small mistake in the way we called 2 functions, in `FiltersSection.changeChromaKey` and `FiltersSection.changeChromaThreshold` what we want is
> > ```
> > viewport.getSelectedShapes().forEach((s) => s.filters[index].setKeyFromHex(value, save));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > viewport.getSelectedShapes().forEach((s) => s.filters[index].setThreshold(value, save));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > not
> > ```
> > viewport.getSelectedShapes().forEach((s) => s.filters[index].setKeyFromHex(value), save);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > emphasis on where the `save` argument is passed.
> > We also may need to change the `Chroma.setKeyFromHex` and `Chroma.setThreshold` method signatures to take in the `save` parameter.
> > BTW, this mistake has been there even before this PR.
> 
> Yes, this was just copied over during the refactoring. I've updated the code to reflect your proposed changes

We may also need to change the `Chroma.setKeyFromHex` and `Chroma.setThreshold` method signatures to take in the save parameter, so it will be consistent with other shape modifying methods.

Thank you Pieter.

**Comment by gniziemazity** [comment]
Wow. Amazing update!

**Pull request merged**
